FLEURS_TO_FLORES = {
    "af_za": "afr_Latn",
    "am_et": "amh_Ethi",
    "ar_eg": "arb_Arab",
    "as_in": "asm_Beng",
    "ast_es": "ast_Latn",
    "az_az": "azj_Latn",
    "be_by": "bel_Cyrl",
    "bg_bg": "bul_Cyrl",
    "bn_in": "ben_Beng",
    "bs_ba": "bos_Latn",
    "ca_es": "cat_Latn",
    "ceb_ph": "ceb_Latn",
    "ckb_iq": "ckb_Arab",
    "cmn_hans_cn": "zho_Hans",
    "cs_cz": "ces_Latn",
    "cy_gb": "cym_Latn",
    "da_dk": "dan_Latn",
    "de_de": "deu_Latn",
    "el_gr": "ell_Grek",
    "en_us": "eng_Latn",
    "es_419": "spa_Latn",
    "et_ee": "est_Latn",
    "fa_ir": "pes_Arab",
    "fi_fi": "fin_Latn",
    "fil_ph": "tgl_Latn",
    "fr_fr": "fra_Latn",
    "ga_ie": "gle_Latn",
    "gl_es": "glg_Latn",
    "gu_in": "guj_Gujr",
    "ha_ng": "hau_Latn",
    "he_il": "heb_Hebr",
    "hi_in": "hin_Deva",
    "hr_hr": "hrv_Latn",
    "hu_hu": "hun_Latn",
    "hy_am": "hye_Armn",
    "id_id": "ind_Latn",
    "ig_ng": "ibo_Latn",
    "is_is": "isl_Latn",
    "it_it": "ita_Latn",
    "ja_jp": "jpn_Jpan",
    "jv_id": "jav_Latn",
    "ka_ge": "kat_Geor",
    "kam_ke": "kam_Latn",
    "kea_cv": "kea_Latn",
    "kk_kz": "kaz_Cyrl",
    "km_kh": "khm_Khmr",
    "kn_in": "kan_Knda",
    "ko_kr": "kor_Hang",
    "ky_kg": "kir_Cyrl",
    "lb_lu": "ltz_Latn",
    "lg_ug": "lug_Latn",
    "ln_cd": "lin_Latn",
    "lo_la": "lao_Laoo",
    "lt_lt": "lit_Latn",
    "luo_ke": "luo_Latn",
    "lv_lv": "lvs_Latn",
    "mi_nz": "mri_Latn",
    "mk_mk": "mkd_Cyrl",
    "ml_in": "mal_Mlym",
    "mn_mn": "khk_Cyrl",
    "mr_in": "mar_Deva",
    "ms_my": "zsm_Latn",
    "mt_mt": "mlt_Latn",
    "my_mm": "mya_Mymr",
    "nb_no": "nob_Latn",
    "ne_np": "npi_Deva",
    "nl_nl": "nld_Latn",
    "nso_za": "nso_Latn",
    "ny_mw": "nya_Latn",
    "oc_fr": "oci_Latn",
    "or_in": "ory_Orya",
    "pa_in": "pan_Guru",
    "pl_pl": "pol_Latn",
    "ps_af": "pbt_Arab",
    "pt_br": "por_Latn",
    "ro_ro": "ron_Latn",
    "ru_ru": "rus_Cyrl",
    "sd_in": "snd_Arab",
    "sk_sk": "slk_Latn",
    "sl_si": "slv_Latn",
    "sn_zw": "sna_Latn",
    "so_so": "som_Latn",
    "sr_rs": "srp_Cyrl",
    "sv_se": "swe_Latn",
    "sw_ke": "swh_Latn",
    "ta_in": "tam_Taml",
    "te_in": "tel_Telu",
    "tg_tj": "tgk_Cyrl",
    "th_th": "tha_Thai",
    "tr_tr": "tur_Latn",
    "uk_ua": "ukr_Cyrl",
    "umb_ao": "umb_Latn",
    "ur_pk": "urd_Arab",
    "uz_uz": "uzn_Latn",
    "vi_vn": "vie_Latn",
    "wo_sn": "wol_Latn",
    "xh_za": "xho_Latn",
    "yo_ng": "yor_Latn",
    "yue_hant_hk": "zho_Hant",
    "zu_za": "zul_Latn",
    "ff_sn": "fuv_Latn",  # Fulah - Nigeria mapped to Fulah - Senegal
    "om_et": "gaz_Latn",  # Oromo - West Central mapped to Oromo - Ethiopia
}


BELEBELE = [
    "acm_Arab",
    "afr_Latn",
    "als_Latn",
    "amh_Ethi",
    "apc_Arab",
    "arb_Arab",
    "arb_Latn",
    "ars_Arab",
    "ary_arab",
    "arz_Arab",
    "asm_Beng",
    "azj_Latn",
    "bam_Latn",
    "ben_Beng",
    "ben_Latn",
    "bod_Tibt",
    "bul_Cyrl",
    "cat_Latn",
    "ceb_Latn",
    "ces_Latn",
    "ckb_Arab",
    "dan_Latn",
    "deu_Latn",
    "ell_Grek",
    "eng_Latn",
    "est_Latn",
    "eus_Latn",
    "fin_Latn",
    "fra_Latn",
    "fuv_Latn",
    "gaz_Latn",
    "grn_Latn",
    "guj_Gujr",
    "hat_Latn",
    "hau_Latn",
    "heb_Hebr",
    "hin_Deva",
    "hin_Latn",
    "hrv_Latn",
    "hun_Latn",
    "hye_Armn",
    "ibo_Latn",
    "ilo_Latn",
    "ind_Latn",
    "isl_Latn",
    "ita_Latn",
    "jav_Latn",
    "jpn_Jpan",
    "kac_Latn",
    "kan_Knda",
    "kat_Geor",
    "kaz_Cyrl",
    "kea_Latn",
    "khk_Cyrl",
    "khm_Khmr",
    "kin_Latn",
    "kir_Cyrl",
    "kor_Hang",
    "lao_Laoo",
    "lin_Latn",
    "lit_Latn",
    "lug_Latn",
    "luo_Latn",
    "lvs_Latn",
    "mal_Mlym",
    "mar_Deva",
    "mkd_Cyrl",
    "mlt_Latn",
    "mri_Latn",
    "mya_Mymr",
    "nld_Latn",
    "nob_Latn",
    "npi_Deva",
    "npi_Latn",
    "nso_Latn",
    "nya_Latn",
    "ory_Orya",
    "pan_Guru",
    "pbt_Arab",
    "pes_Arab",
    "plt_Latn",
    "pol_Latn",
    "por_Latn",
    "ron_Latn",
    "rus_Cyrl",
    "shn_Mymr",
    "sin_Latn",
    "sin_Sinh",
    "slk_Latn",
    "slv_Latn",
    "sna_Latn",
    "snd_Arab",
    "som_Latn",
    "sot_Latn",
    "spa_Latn",
    "srp_Cyrl",
    "ssw_Latn",
    "sun_Latn",
    "swe_Latn",
    "swh_Latn",
    "tam_Taml",
    "tel_Telu",
    "tgk_Cyrl",
    "tgl_Latn",
    "tha_Thai",
    "tir_Ethi",
    "tsn_Latn",
    "tso_Latn",
    "tur_Latn",
    "ukr_Cyrl",
    "urd_Arab",
    "urd_Latn",
    "uzn_Latn",
    "vie_Latn",
    "war_Latn",
    "wol_Latn",
    "xho_Latn",
    "yor_Latn",
    "zho_Hans",
    "zho_Hant",
    "zsm_Latn",
    "zul_Latn",
]

# old more comprehensive version (incl. speaker IDs) has slightly
# different nameing convention for
# "old": "new" --
#    "rup_bg": "bg_bg",
#    "ku_arab_iq": "ckb_iq",
#    "oci_fr": "oc_fr",
#    "sd_arab_in": "sd_in",
FLEURS_DL = sorted(
    [
        "af_za",
        "am_et",
        "ar_eg",
        "as_in",
        "ast_es",
        "az_az",
        "be_by",
        "bn_in",
        "bs_ba",
        "ca_es",
        "ceb_ph",
        "cmn_hans_cn",
        "yue_hant_hk",
        "cs_cz",
        "cy_gb",
        "da_dk",
        "de_de",
        "el_gr",
        "en_us",
        "es_419",
        "et_ee",
        "fa_ir",
        "ff_sn",
        "fi_fi",
        "fil_ph",
        "fr_fr",
        "ga_ie",
        "gl_es",
        "gu_in",
        "ha_ng",
        "he_il",
        "hi_in",
        "hr_hr",
        "hu_hu",
        "hy_am",
        "id_id",
        "ig_ng",
        "is_is",
        "it_it",
        "ja_jp",
        "jv_id",
        "ka_ge",
        "kam_ke",
        "kea_cv",
        "kk_kz",
        "km_kh",
        "kn_in",
        "ko_kr",
        "ku_arab_iq",
        "ky_kg",
        "lb_lu",
        "lg_ug",
        "ln_cd",
        "lo_la",
        "lt_lt",
        "luo_ke",
        "lv_lv",
        "mi_nz",
        "mk_mk",
        "ml_in",
        "mn_mn",
        "mr_in",
        "ms_my",
        "mt_mt",
        "my_mm",
        "nb_no",
        "ne_np",
        "nl_nl",
        "nso_za",
        "ny_mw",
        "oci_fr",
        "om_et",
        "or_in",
        "pa_in",
        "pl_pl",
        "ps_af",
        "pt_br",
        "ro_ro",
        "ru_ru",
        "rup_bg",
        "sd_arab_in",
        "sk_sk",
        "sl_si",
        "sn_zw",
        "so_so",
        "sr_rs",
        "sv_se",
        "sw_ke",
        "ta_in",
        "te_in",
        "tg_tj",
        "th_th",
        "tr_tr",
        "uk_ua",
        "umb_ao",
        "ur_pk",
        "uz_uz",
        "vi_vn",
        "wo_sn",
        "xh_za",
        "yo_ng",
        "zu_za",
    ]
)


FLEURS = [
    "af_za",
    "am_et",
    "ar_eg",
    "as_in",
    "ast_es",
    "az_az",
    "be_by",
    "bg_bg",
    "bn_in",
    "bs_ba",
    "ca_es",
    "ceb_ph",
    "ckb_iq",
    "cmn_hans_cn",
    "cs_cz",
    "cy_gb",
    "da_dk",
    "de_de",
    "el_gr",
    "en_us",
    "es_419",
    "et_ee",
    "fa_ir",
    "ff_sn",
    "fi_fi",
    "fil_ph",
    "fr_fr",
    "ga_ie",
    "gl_es",
    "gu_in",
    "ha_ng",
    "he_il",
    "hi_in",
    "hr_hr",
    "hu_hu",
    "hy_am",
    "id_id",
    "ig_ng",
    "is_is",
    "it_it",
    "ja_jp",
    "jv_id",
    "ka_ge",
    "kam_ke",
    "kea_cv",
    "kk_kz",
    "km_kh",
    "kn_in",
    "ko_kr",
    "ky_kg",
    "lb_lu",
    "lg_ug",
    "ln_cd",
    "lo_la",
    "lt_lt",
    "luo_ke",
    "lv_lv",
    "mi_nz",
    "mk_mk",
    "ml_in",
    "mn_mn",
    "mr_in",
    "ms_my",
    "mt_mt",
    "my_mm",
    "nb_no",
    "ne_np",
    "nl_nl",
    "nso_za",
    "ny_mw",
    "oc_fr",
    "om_et",
    "or_in",
    "pa_in",
    "pl_pl",
    "ps_af",
    "pt_br",
    "ro_ro",
    "ru_ru",
    "sd_in",
    "sk_sk",
    "sl_si",
    "sn_zw",
    "so_so",
    "sr_rs",
    "sv_se",
    "sw_ke",
    "ta_in",
    "te_in",
    "tg_tj",
    "th_th",
    "tr_tr",
    "uk_ua",
    "umb_ao",
    "ur_pk",
    "uz_uz",
    "vi_vn",
    "wo_sn",
    "xh_za",
    "yo_ng",
    "yue_hant_hk",
    "zu_za",
]
